version: '3.9'

services:
  frontend:
    build: ./frontend
    ports:
      - "3030:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/tasks
    depends_on:
      - db
    ports:
      - "5050:5000"

  db:
    image: ankane/pgvector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks
    ports:
      - "5432:5432"
